# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-14T13:27:08+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, constr
from enum import Enum
from typing import Any


class DisableResponseSchema(BaseModel):
    """
    Whether the account was disabled, or already was.

    `changed` is false for a revocation that was already in force, which must
    not read as a revocation that just happened.
    """
    changed: bool = Field(..., title='Changed')
    user_id: str = Field(..., title='User Id')
    username: str = Field(..., title='Username')


class DivergenceModelSchema(BaseModel):
    """
    One member whose Keycloak state does not match the registry.
    """
    detail: str | None = Field('', title='Detail')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    username: str = Field(..., title='Username')


class ErrorDetailSchema(BaseModel):
    """
    `detail` in every error body except `422`, which is FastAPI's own list.

    `message` is the service's sentence, naming the member or the scope. It is
    for a log or an operator, and it is not a contract.

    **`code` is a string, not an enum, on purpose.** A generated client turns an
    enum into a strict type that raises on a value it has never seen, so every
    new code would break every consumer that has not regenerated — on the error
    path, where a crash hides the refusal it was meant to report. The codes are
    listed in the description and in `docs/api-reference.md`.
    """
    code: str = Field(..., description='Stable machine-readable reason: `missing_token`, `invalid_token`, `insufficient_scope`, `community_not_found`, `member_not_found`, `account_not_found`, `account_disabled`, `has_password`, `no_password`, `no_email`, `cooldown`, `reconcile_diverged`, `registry_unavailable`, `send_failed`, `provisioning_failed`. New codes may be added: branch on the HTTP status for one you do not know.', title='Code')
    message: str = Field(..., description='A human sentence. Not a contract.', title='Message')


class ErrorResponseSchema(BaseModel):
    """
    `{"detail": {"code": "...", "message": "..."}}`.

    `detail` stays the top-level key, so a consumer that already reads
    `detail` keeps finding it; it is an object rather than a string.
    """
    detail: ErrorDetailSchema


class InvitationIntentSchema(Enum):
    """
    Which email the caller of `POST .../invitation` asks for.

    Explicit, and required, so the email is always the button a person pressed
    (requester, 2026-09-14, A2: "do not trick the user"). The service checks it
    against the account in the same call that sends and refuses a mismatch.
    """
    invitation = 'invitation'
    password_reset = 'password_reset'


class InvitationOutcomeSchema(Enum):
    """
    Why an upsert did, or did not, send an invitation.

    Mirrors `celine.provisioning.invitation.InvitationOutcome`. A stable reason
    code the consumer translates for the operator who approved.
    """
    not_requested = 'not_requested'
    sent = 'sent'
    has_password = 'has_password'
    not_on_dev_list = 'not_on_dev_list'
    account_disabled = 'account_disabled'
    cooldown = 'cooldown'
    send_failed = 'send_failed'
    no_email = 'no_email'


class InvitationRequestSchema(BaseModel):
    """
    The body of `POST /participants/{community}/{key}/invitation`.
    """
    intent: InvitationIntentSchema = Field(..., description='`invitation`: set a first password (`UPDATE_PASSWORD` + `VERIFY_EMAIL`, 7 days); refused `409 has_password` when the account has one. `password_reset`: replace it (`UPDATE_PASSWORD`, 1 hour); refused `409 no_password` when the account has none. Never turned into the other.')


class InvitationSendOutcomeSchema(Enum):
    """
    What `POST .../invitation` did: sent, or refused by the dev list.
    """
    sent = 'sent'
    not_on_dev_list = 'not_on_dev_list'


class LocaleSchema(Enum):
    """
    The languages the email and login themes carry.

    Keycloak stores any value it is given and silently falls back to the realm
    default for one it has no bundle for (measured), so the check is here.
    """
    it = 'it'
    en = 'en'
    es = 'es'


class ParticipantResponseSchema(BaseModel):
    """
    What the caller cannot compute and has to be told.
    """
    created: bool = Field(..., description='Whether this call created the account. A retry returns false.', title='Created')
    invitation: InvitationOutcomeSchema = Field(..., description='What happened to the invitation: `not_requested` (invite was false), `sent`, `has_password` (nothing to invite to), `not_on_dev_list` (dev email mode, address not allowed), `no_email` (the account has no email address, whatever the mode), `account_disabled`, `cooldown` (this account was emailed within the cooldown; nothing sent), `send_failed` (Keycloak did not send it; no cooldown started, so a retry may send). New codes may be added: show an unknown one raw.')
    invited: bool = Field(..., description='True if and only if `invitation` is `sent`.', title='Invited')
    user_id: str = Field(..., description="The Keycloak uuid of the account (not the registry's user_id)", title='User Id')
    username: str = Field(..., description="What this account authenticates as, read back from Keycloak. This is the value that becomes the registry's Member.user_id.", title='Username')


class ParticipantUpsertSchema(BaseModel):
    """
    The body of `PUT /participants/{community}/{key}`.

    **The email transits and is stored nowhere.** Not here — this service keeps
    no state at all — and not in the registry, which has no email column and is
    gaining none. It is on the account in Keycloak, which is where the address a
    person logs in with belongs.

    It is required because it is the only thing that can find an account this
    platform did not name. A participant who already has a login authenticates
    under whatever convention created it, and the address is the one identifier
    every writer agrees on.

    **A plain string, not `EmailStr`.** The address belongs to the submission
    `../onboarding` already validated and accepted; re-deciding here whether it
    is well formed would mean a person who has been approved cannot be given a
    login because two libraries disagree about their address. Non-empty is the
    whole check, and it exists so a missing value fails here rather than
    creating an account named the empty string.
    """
    email: constr(min_length=1) = Field(..., description="The participant's address; used to find or create the account", title='Email')
    first_name: str | None = Field(None, description='Given name, optional', title='First Name')
    invite: bool | None = Field(False, description='Email the participant an invitation to set their password — only if the account was created in this call or has no password. Never a reset. The outcome is in `invitation`; the upsert never fails because of it.', title='Invite')
    last_name: str | None = Field(None, description='Family name, optional', title='Last Name')
    locale: LocaleSchema | None = Field(None, description="The participant's language, used for Keycloak's emails. Written on creation, and on an existing account only if it has none. Needs internationalization enabled on the realm, or Keycloak drops it.")


class ReconcileResponseSchema(BaseModel):
    """
    What a community sweep did, and what it could not put right.

    `divergences` is empty on a healthy run **and a sweep that ends with any is
    a failure, reported as one**. The check runs after provisioning, so anything
    it finds is something a provisioning call claimed to have done and had not:
    quietly repairing it on the next sweep is how 10 of 45 members ended up
    outside their own organization with nothing saying so.
    """
    community: str = Field(..., title='Community')
    created: int = Field(..., title='Created')
    divergences: list[DivergenceModelSchema] | None = Field(None, title='Divergences')
    existing: int = Field(..., title='Existing')
    members: int = Field(..., title='Members')


class ValidationErrorSchema(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')


class InvitationResponseSchema(BaseModel):
    """
    What `POST .../invitation` emailed, and for how long the link lasts.

    No credential travels here: the person sets their own through the link
    Keycloak sends. `actions` says which email it was — `UPDATE_PASSWORD` and
    `VERIFY_EMAIL` for intent `invitation`, `UPDATE_PASSWORD` alone for intent
    `password_reset`.
    """
    actions: list[str] = Field(..., title='Actions')
    invitation: InvitationSendOutcomeSchema = Field(..., description='`sent`, or `not_on_dev_list` when dev email mode refused the address')
    lifespan: int = Field(..., description='Seconds the link stays usable', title='Lifespan')
    user_id: str = Field(..., title='User Id')
    username: str = Field(..., title='Username')
