# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-12T13:01:19+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, constr
from typing import Any


class DisableResponseSchema(BaseModel):
    """
    Whether the account was disabled, or already was.

    `changed` is false for a revocation that was already in force, which must
    not read as a revocation that just happened.
    """
    changed: bool = Field(..., title='Changed')
    user_id: str = Field(..., title='User Id')
    username: str = Field(..., title='Username')


class DivergenceModelSchema(BaseModel):
    """
    One member whose Keycloak state does not match the registry.
    """
    detail: str | None = Field('', title='Detail')
    key: str = Field(..., title='Key')
    kind: str = Field(..., title='Kind')
    username: str = Field(..., title='Username')


class ParticipantResponseSchema(BaseModel):
    """
    What the caller cannot compute and has to be told.
    """
    created: bool = Field(..., description='Whether this call created the account. A retry returns false.', title='Created')
    user_id: str = Field(..., description="The Keycloak uuid of the account (not the registry's user_id)", title='User Id')
    username: str = Field(..., description="What this account authenticates as, read back from Keycloak. This is the value that becomes the registry's Member.user_id.", title='Username')


class ParticipantUpsertSchema(BaseModel):
    """
    The body of `PUT /participants/{community}/{key}`.

    **The email transits and is stored nowhere.** Not here — this service keeps
    no state at all — and not in the registry, which has no email column and is
    gaining none. It is on the account in Keycloak, which is where the address a
    person logs in with belongs.

    It is required because it is the only thing that can find an account this
    platform did not name. A participant who already has a login authenticates
    under whatever convention created it, and the address is the one identifier
    every writer agrees on.

    **A plain string, not `EmailStr`.** The address belongs to the submission
    `../onboarding` already validated and accepted; re-deciding here whether it
    is well formed would mean a person who has been approved cannot be given a
    login because two libraries disagree about their address. Non-empty is the
    whole check, and it exists so a missing value fails here rather than
    creating an account named the empty string.
    """
    email: constr(min_length=1) = Field(..., description="The participant's address; used to find or create the account", title='Email')
    first_name: str | None = Field(None, description='Given name, optional', title='First Name')
    last_name: str | None = Field(None, description='Family name, optional', title='Last Name')


class PasswordResetResponseSchema(BaseModel):
    """
    The one-time credential, and who it belongs to.

    Temporary by construction: the participant is made to change it at next
    login, so what travels back here is a handover and never their password.
    """
    temporary_password: str = Field(..., title='Temporary Password')
    user_id: str = Field(..., title='User Id')
    username: str = Field(..., title='Username')


class ReconcileResponseSchema(BaseModel):
    """
    What a community sweep did, and what it could not put right.

    `divergences` is empty on a healthy run **and a sweep that ends with any is
    a failure, reported as one**. The check runs after provisioning, so anything
    it finds is something a provisioning call claimed to have done and had not:
    quietly repairing it on the next sweep is how 10 of 45 members ended up
    outside their own organization with nothing saying so.
    """
    community: str = Field(..., title='Community')
    created: int = Field(..., title='Created')
    divergences: list[DivergenceModelSchema] | None = Field(None, title='Divergences')
    existing: int = Field(..., title='Existing')
    members: int = Field(..., title='Members')


class ValidationErrorSchema(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')
