services:
  digital-twin:
    package: dt
    openapi: http://api.celine.localhost/dt/openapi.json
  datasets:
    openapi: http://api.celine.localhost/datasets/openapi.json
  rec-registry:
    package: rec_registry
    openapi: http://api.celine.localhost/rec-registry/openapi.json
