version: "3"

tasks:
  setup:
    desc: Setup
    cmds:
      - uv sync

  test:
    desc: "Run tests"
    cmds:
      - uv run pytest -- {{.CLI_ARGS}}

  release:
    cmds:
      - uv run semantic-release -v version --no-vcs-release
      - git push
      - git push --tags

  gen:
    cmds:
      - uv run celine-sdk spec fetch
      - uv run celine-sdk generate
