# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-04-04T15:51:12+00:00

from __future__ import annotations
from pydantic import BaseModel, Field
from datetime import datetime
from uuid import UUID
from enum import Enum
from typing import Any


class CommitmentCreateSchema(BaseModel):
    community_id: str | None = Field(None, title='Community Id')
    device_id: str | None = Field(None, title='Device Id')
    period_end: datetime = Field(..., title='Period End')
    period_start: datetime = Field(..., title='Period Start')
    reward_points_estimated: int | None = Field(0, title='Reward Points Estimated')
    suggestion_id: str = Field(..., title='Suggestion Id')
    suggestion_type: str | None = Field('shift-consumption', title='Suggestion Type')
    user_id: str = Field(..., title='User Id')


class StatusSchema(Enum):
    committed = 'committed'
    settled = 'settled'
    rejected = 'rejected'
    cancelled = 'cancelled'


class CommitmentOutSchema(BaseModel):
    committed_at: datetime = Field(..., title='Committed At')
    community_id: str | None = Field(..., title='Community Id')
    device_id: str | None = Field(..., title='Device Id')
    id: UUID = Field(..., title='Id')
    period_end: datetime = Field(..., title='Period End')
    period_start: datetime = Field(..., title='Period Start')
    reminded_at: datetime | None = Field(..., title='Reminded At')
    reward_points_actual: int | None = Field(..., title='Reward Points Actual')
    reward_points_estimated: int = Field(..., title='Reward Points Estimated')
    settled_at: datetime | None = Field(..., title='Settled At')
    status: StatusSchema = Field(..., title='Status')
    suggestion_id: str = Field(..., title='Suggestion Id')
    suggestion_type: str = Field(..., title='Suggestion Type')
    user_id: str = Field(..., title='User Id')


class CommitmentSettleSchema(BaseModel):
    actual_kwh: float | None = Field(None, title='Actual Kwh')
    reward_points_actual: int = Field(..., title='Reward Points Actual')


class SuggestionItemSchema(BaseModel):
    clock_range: str = Field(..., title='Clock Range')
    confidence: float = Field(..., title='Confidence')
    from_period: str = Field(..., title='From Period')
    id: str = Field(..., title='Id')
    impact_kwh_estimated: float = Field(..., title='Impact Kwh Estimated')
    period_end: str = Field(..., title='Period End')
    period_start: str = Field(..., title='Period Start')
    reward_points: int = Field(..., title='Reward Points')
    suggestion_type: str = Field(..., title='Suggestion Type')
    to_is_tomorrow: bool = Field(..., title='To Is Tomorrow')
    to_period: str = Field(..., title='To Period')
    to_time: str = Field(..., title='To Time')


class ResponseSchema(Enum):
    accepted = 'accepted'
    declined = 'declined'


class SuggestionRespondRequestSchema(BaseModel):
    period_end: str | None = Field(None, title='Period End')
    period_start: str | None = Field(None, title='Period Start')
    response: ResponseSchema = Field(..., title='Response')
    reward_points: int | None = Field(None, title='Reward Points')


class StatusSchema1(Enum):
    committed = 'committed'
    declined = 'declined'


class SuggestionRespondResponseSchema(BaseModel):
    commitment_id: UUID | None = Field(None, title='Commitment Id')
    reward_points_estimated: int = Field(..., title='Reward Points Estimated')
    status: StatusSchema1 = Field(..., title='Status')


class ValidationErrorSchema(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class CommitmentListResponseSchema(BaseModel):
    items: list[CommitmentOutSchema] = Field(..., title='Items')
    total: int = Field(..., title='Total')


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')
