"""Generated OpenAPI clients.

One subpackage per service declared in `services.yaml`, e.g.
`celine.sdk.openapi.dt` and `celine.sdk.openapi.rec_registry`.

Generated by `celine-sdk generate` from the specs under `openapi/`, and
replaced wholesale each time — never hand-edited. The set of subpackages here
is exactly the set of services in the manifest: a package with no entry is
frozen at whenever it was last generated, and a test asserts neither can happen
(see docs/specifications/spec-management.md).
"""
