# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-03T07:20:27+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, conint
from datetime import date, datetime
from typing import Any


class AdminNotificationOutSchema(BaseModel):
    """
    Admin view – same fields, explicit class for OpenAPI separation.
    """
    id: str = Field(..., title='Id')
    nudge_log_id: str | None = Field(None, title='Nudge Log Id')
    rule_id: str = Field(..., title='Rule Id')
    user_id: str = Field(..., title='User Id')
    family: str = Field(..., title='Family')
    type: str = Field(..., title='Type')
    severity: str = Field(..., title='Severity')
    title: str = Field(..., title='Title')
    body: str = Field(..., title='Body')
    status: str = Field(..., title='Status')
    read_at: datetime | None = Field(None, title='Read At')
    clicked_at: datetime | None = Field(None, title='Clicked At')
    click_action: str | None = Field(None, title='Click Action')
    deleted_at: datetime | None = Field(None, title='Deleted At')
    created_at: datetime = Field(..., title='Created At')


class AnalyticsDeliveryFailureSchema(BaseModel):
    channel: str = Field(..., description='webpush | email', title='Channel')
    error_class: str = Field(..., title='Error Class')
    count: conint(ge=0) = Field(..., title='Count')


class AnalyticsFunnelStepSchema(BaseModel):
    id: str = Field(..., description='sent | delivered | read | clicked | committed', title='Id')
    count: conint(ge=0) = Field(..., title='Count')


class AnalyticsReachabilitySchema(BaseModel):
    channel: str = Field(..., description='webpush | email', title='Channel')
    reachable: conint(ge=0) = Field(..., title='Reachable')
    total: conint(ge=0) = Field(..., title='Total')
    opted_out: conint(ge=0) = Field(..., title='Opted Out')


class AnalyticsRuleMetricSchema(BaseModel):
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    family: str = Field(..., title='Family')
    channel: str = Field(..., description='webpush | email', title='Channel')
    severity: str = Field(..., title='Severity')
    active: bool = Field(..., title='Active')
    last_fired_at: datetime | None = Field(None, title='Last Fired At')
    volume: conint(ge=0) = Field(..., title='Volume')
    steps: list[AnalyticsFunnelStepSchema] = Field(..., title='Steps')


class CommunityNudgingAnalyticsOutSchema(BaseModel):
    """
    Privacy-safe, REC-scoped input for the manager dashboard.
    """
    community_id: str = Field(..., title='Community Id')
    start: date = Field(..., title='Start')
    end: date = Field(..., title='End')
    steps: list[AnalyticsFunnelStepSchema] = Field(..., title='Steps')
    rules: list[AnalyticsRuleMetricSchema] = Field(..., title='Rules')
    failures: list[AnalyticsDeliveryFailureSchema] = Field(..., title='Failures')
    reachability: list[AnalyticsReachabilitySchema] = Field(..., title='Reachability')


class DeliveryJobOutSchema(BaseModel):
    job_id: str = Field(..., title='Job Id')
    user_id: str = Field(..., title='User Id')
    rule_id: str = Field(..., title='Rule Id')
    nudge_id: str = Field(..., title='Nudge Id')
    channel: str = Field(..., title='Channel')
    destination: str = Field(..., title='Destination')
    title: str = Field(..., title='Title')
    body: str = Field(..., title='Body')
    dedup_key: str = Field(..., title='Dedup Key')
    created_at: datetime = Field(..., title='Created At')


class DigitalTwinEventSchema(BaseModel):
    event_type: str = Field(..., title='Event Type')
    timestamp: datetime | None = Field(None, title='Timestamp')
    user_id: str | None = Field(None, title='User Id')
    community_id: str | None = Field(None, title='Community Id')
    payload: dict[str, Any] | None = Field(None, title='Payload')
    facts: dict[str, Any] | None = Field(None, description='Enriched facts computed by Digital Twin', title='Facts')


class EngineResultOutSchema(BaseModel):
    status: str = Field(..., title='Status')
    reason: str | None = Field(None, title='Reason')
    details: dict[str, Any] | None = Field(None, title='Details')


class IngestErrorDetailSchema(BaseModel):
    error: str = Field(..., title='Error')
    reason: str | None = Field(None, title='Reason')
    errors: list[str] | None = Field(None, title='Errors')
    results: list[EngineResultOutSchema] | None = Field(None, title='Results')


class NotificationClickTrackInSchema(BaseModel):
    token: str = Field(..., title='Token')
    action: str | None = Field(None, description='Notification action identifier; empty means default notification body click', title='Action')


class NotificationKindPreferenceOutSchema(BaseModel):
    kind: str = Field(..., title='Kind')
    label: str = Field(..., title='Label')
    description: str = Field(..., title='Description')
    cadence: str = Field(..., title='Cadence')
    enabled: bool = Field(..., title='Enabled')
    editable: bool | None = Field(True, title='Editable')


class NotificationOutSchema(BaseModel):
    """
    User-facing notification. Fields are proper columns, not buried JSON.
    """
    id: str = Field(..., title='Id')
    nudge_log_id: str | None = Field(None, description='Originating engine audit row', title='Nudge Log Id')
    rule_id: str = Field(..., title='Rule Id')
    user_id: str = Field(..., title='User Id')
    family: str = Field(..., description='energy | onboarding | seasonal | …', title='Family')
    type: str = Field(..., description='informative | opportunity | alert', title='Type')
    severity: str = Field(..., description='info | warning | critical', title='Severity')
    title: str = Field(..., title='Title')
    body: str = Field(..., title='Body')
    status: str = Field(..., description='pending | sent | suppressed | failed', title='Status')
    read_at: datetime | None = Field(None, description='Null if unread', title='Read At')
    clicked_at: datetime | None = Field(None, description='Null if the push was never clicked', title='Clicked At')
    click_action: str | None = Field(None, description='Action identifier reported by the notification click event', title='Click Action')
    deleted_at: datetime | None = Field(None, description='Null if not soft-deleted', title='Deleted At')
    created_at: datetime = Field(..., title='Created At')


class NudgeCreatedItemSchema(BaseModel):
    nudge_id: str = Field(..., title='Nudge Id')
    rule_id: str = Field(..., title='Rule Id')
    deliveries: list[DeliveryJobOutSchema] = Field(..., title='Deliveries')


class ScheduledEventCreateRequestSchema(BaseModel):
    event_type: str = Field(..., title='Event Type')
    user_id: str = Field(..., title='User Id')
    community_id: str | None = Field(None, title='Community Id')
    external_key: str | None = Field(None, title='External Key')
    trigger_at: datetime = Field(..., title='Trigger At')
    facts: dict[str, Any] | None = Field(None, title='Facts')


class ScheduledEventOutSchema(BaseModel):
    id: str = Field(..., title='Id')
    event_type: str = Field(..., title='Event Type')
    user_id: str = Field(..., title='User Id')
    community_id: str | None = Field(None, title='Community Id')
    external_key: str | None = Field(None, title='External Key')
    trigger_at: datetime = Field(..., title='Trigger At')
    status: str = Field(..., title='Status')
    created_at: datetime = Field(..., title='Created At')
    dispatched_at: datetime | None = Field(None, title='Dispatched At')


class SeedApplyRequestSchema(BaseModel):
    rules: list[dict[str, Any]] | None = Field([], title='Rules')
    templates: list[dict[str, Any]] | None = Field([], title='Templates')
    preferences: list[dict[str, Any]] | None = Field([], title='Preferences')
    overrides: list[dict[str, Any]] | None = Field([], title='Overrides')


class SeedApplyResponseSchema(BaseModel):
    status: str | None = Field('ok', title='Status')
    rules: int = Field(..., title='Rules')
    templates: int = Field(..., title='Templates')
    preferences: int = Field(..., title='Preferences')
    overrides: int = Field(..., title='Overrides')


class SendTestRequestSchema(BaseModel):
    """
    Admin-only: user_id is explicit because an admin targets any user.
    """
    user_id: str = Field(..., description='Target user ID', title='User Id')
    community_id: str | None = Field(None, description='Optional community scope for the test send', title='Community Id')
    title: str | None = Field('Test', examples=['Test'], title='Title')
    body: str | None = Field('Hello!', examples=['Hello!'], title='Body')
    url: str | None = Field('/', examples=['/'], title='Url')


class SendTestResponseSchema(BaseModel):
    status: str = Field(..., title='Status')
    sent: int | None = Field(None, title='Sent')
    failed: int | None = Field(None, title='Failed')
    notification_id: str | None = Field(None, title='Notification Id')


class StatusResponseSchema(BaseModel):
    status: str = Field(..., examples=['ok'], title='Status')


class UnsubscribeRequestSchema(BaseModel):
    """
    user_id is derived from the JWT – not accepted from the caller.
    """
    endpoint: str = Field(..., title='Endpoint')
    community_id: str | None = Field(None, description='Optional community scope for the subscription', title='Community Id')


class UserPreferenceOutSchema(BaseModel):
    lang: str | None = Field('en', title='Lang')
    max_per_day: conint(ge=1, le=10) = Field(..., title='Max Per Day')
    channel_email: bool | None = Field(False, title='Channel Email')
    email: str | None = Field(None, title='Email')
    enabled_notification_kinds: list[str] | None = Field(None, title='Enabled Notification Kinds')


class UserPreferenceUpdateInSchema(BaseModel):
    max_per_day: conint(ge=1, le=10) = Field(..., title='Max Per Day')
    lang: str | None = Field(None, title='Lang')
    channel_email: bool | None = Field(None, title='Channel Email')
    email: str | None = Field(None, title='Email')
    enabled_notification_kinds: list[str] | None = Field(None, title='Enabled Notification Kinds')


class ValidationErrorSchema(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class VapidPublicKeyResponseSchema(BaseModel):
    public_key: str = Field(..., title='Public Key')


class WebPushKeysInSchema(BaseModel):
    p256dh: str = Field(..., title='P256Dh')
    auth: str = Field(..., title='Auth')


class WebPushSubscriptionInSchema(BaseModel):
    endpoint: str = Field(..., title='Endpoint')
    keys: WebPushKeysInSchema


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')


class IngestAcceptedResponseSchema(BaseModel):
    status: str | None = Field('accepted', examples=['accepted'], title='Status')
    delivery: str | None = Field('suppressed', examples=['suppressed'], title='Delivery')
    created: list[NudgeCreatedItemSchema] = Field(..., title='Created')
    suppressed: list[EngineResultOutSchema] = Field(..., title='Suppressed')


class IngestOkResponseSchema(BaseModel):
    status: str | None = Field('ok', examples=['ok'], title='Status')
    created: list[NudgeCreatedItemSchema] = Field(..., title='Created')
    suppressed: list[EngineResultOutSchema] = Field(..., title='Suppressed')


class SubscribeRequestSchema(BaseModel):
    """
    user_id is derived from the JWT – not accepted from the caller.
    """
    subscription: WebPushSubscriptionInSchema
    community_id: str | None = Field(None, description='Optional community scope for the subscription', title='Community Id')
