# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-07-28T10:46:53+00:00

from __future__ import annotations
from pydantic import BaseModel, Extra, Field
from typing import Any


class AssetDetailSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    name: str = Field(..., title='Name')
    owner_key: str = Field(..., title='Owner Key')
    owner_user_id: str = Field(..., title='Owner User Id')
    sensor_id: str | None = Field(None, title='Sensor Id')
    properties: dict[str, Any] | None = Field(None, title='AssetDetailProperties')
    device: dict[str, Any] | None = Field(None, title='AssetDetailDevice')
    relationships: dict[str, Any] | None = Field(None, title='AssetDetailRelationships')
    extra: dict[str, Any] | None = Field(None, title='AssetDetailExtra')
    created_at: str | None = Field(None, title='Created At')
    updated_at: str | None = Field(None, title='Updated At')


class AssetListItemSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    name: str = Field(..., title='Name')
    owner_key: str = Field(..., title='Owner Key')
    owner_user_id: str = Field(..., title='Owner User Id')
    sensor_id: str | None = Field(None, title='Sensor Id')
    device_type: str | None = Field(None, title='Device Type')


class AssetRefSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    name: str = Field(..., title='Name')
    sensor_id: str | None = Field(None, title='Sensor Id')


class AssetRelationshipsInSchema(BaseModel):
    """
    Relationships between assets.
    """
    class Config:
        extra = Extra.allow
    measures: list[str] | None = Field(None, title='Measures')
    paired_with: str | None = Field(None, title='Paired With')


class AssetUpsertSchema(BaseModel):
    """
    Create or replace one asset of a member.

    `properties` is validated against the model for `asset_type`, so an EV
    charger cannot be stored with a heat pump's fields.
    """
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    properties: dict[str, Any] | None = Field(None, title='AssetUpsertProperties')


class CommunityPatchSchema(BaseModel):
    """
    Partial update of community metadata.

    Areas and topology are not here: they are collections with their own
    identity, and a patch omitting them must not read as "this community now
    has none".
    """
    name: str | None = Field(None, title='Name')
    description: str | None = Field(None, title='Description')
    legal: dict[str, Any] | None = Field(None, title='Legal')
    links: dict[str, Any] | None = Field(None, title='Links')
    contact: dict[str, Any] | None = Field(None, title='Contact')
    settings: dict[str, Any] | None = Field(None, title='Settings')
    extra: dict[str, Any] | None = Field(None, title='Extra')


class CommunityRefSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')


class ContactInSchema(BaseModel):
    """
    Contact information.
    """
    class Config:
        extra = Extra.allow
    email: str | None = Field(None, title='Email')
    pec: str | None = Field(None, title='Pec')
    phone: str | None = Field(None, title='Phone')
    address: str | None = Field(None, title='Address')


class DeletionReportSchema(BaseModel):
    """
    What a delete did.

    `purged` distinguishes deactivation from erasure — the same endpoint does
    both, and the caller should be able to tell which happened.
    """
    community_key: str = Field(..., title='Community Key')
    member_key: str = Field(..., title='Member Key')
    purged: bool = Field(..., title='Purged')
    status: str | None = Field(None, title='Status')
    assets_removed: int | None = Field(0, title='Assets Removed')


class DeliveryPointSchema(BaseModel):
    id: str = Field(..., title='Id')
    type: str = Field(..., title='Type')
    description: str | None = Field(None, title='Description')
    address: str | None = Field(None, title='Address')
    tariff: str | None = Field(None, title='Tariff')
    active: bool | None = Field(True, title='Active')


class DeliveryPointInSchema(BaseModel):
    """
    Physical delivery point (POD, CUPS, PRM, etc.).
    """
    class Config:
        extra = Extra.allow
    id: str = Field(..., title='Id')
    type: str = Field(..., title='Type')
    description: str | None = Field(None, title='Description')
    address: str | None = Field(None, title='Address')
    tariff: str | None = Field(None, title='Tariff')
    active: bool | None = Field(True, title='Active')


class DeliveryPointWithOwnerSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    type: str = Field(..., title='Type')
    description: str | None = Field(None, title='Description')
    address: str | None = Field(None, title='Address')
    tariff: str | None = Field(None, title='Tariff')
    active: bool | None = Field(True, title='Active')
    member_key: str = Field(..., title='Member Key')
    member_name: str = Field(..., title='Member Name')


class DeliveryPointsResponseSchema(BaseModel):
    delivery_points: list[DeliveryPointSchema] | None = Field(None, title='Delivery Points')


class DeviceInSchema(BaseModel):
    """
    SAREF-inspired device specification.
    """
    class Config:
        extra = Extra.allow
    type: str | None = Field(None, title='Type')
    model: str | None = Field(None, title='Model')
    serial_number: str | None = Field(None, title='Serial Number')
    mac_address: str | None = Field(None, title='Mac Address')
    firmware_version: str | None = Field(None, title='Firmware Version')


class EVChargerAssetInSchema(BaseModel):
    """
    EV charger asset.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    max_power: float = Field(..., title='Max Power')
    charger_type: str = Field(..., title='Charger Type')
    connector_types: list[str] | None = Field(None, title='Connector Types')
    smart_charging: bool | None = Field(None, title='Smart Charging')
    bidirectional: bool | None = Field(None, title='Bidirectional')
    num_ports: int | None = Field(None, title='Num Ports')
    installation_date: str | None = Field(None, title='Installation Date')
    device: DeviceInSchema | None = None
    relationships: AssetRelationshipsInSchema | None = None


class GlobalAssetLookupSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    name: str = Field(..., title='Name')
    sensor_id: str | None = Field(None, title='Sensor Id')
    properties: dict[str, Any] | None = Field(None, title='GlobalAssetLookupProperties')
    device: dict[str, Any] | None = Field(None, title='GlobalAssetLookupDevice')
    relationships: dict[str, Any] | None = Field(None, title='GlobalAssetLookupRelationships')
    owner_key: str = Field(..., title='Owner Key')
    owner_user_id: str = Field(..., title='Owner User Id')
    community_key: str = Field(..., title='Community Key')
    community_name: str = Field(..., title='Community Name')


class GlobalMemberLookupSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')
    delivery_points: list[DeliveryPointSchema] | None = Field(None, title='Delivery Points')
    community_key: str = Field(..., title='Community Key')
    community_name: str = Field(..., title='Community Name')


class HeatPumpAssetInSchema(BaseModel):
    """
    Heat pump asset.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    thermal_power: float = Field(..., title='Thermal Power')
    electrical_power: float | None = Field(None, title='Electrical Power')
    cop: float | None = Field(None, title='Cop')
    eer: float | None = Field(None, title='Eer')
    scop: float | None = Field(None, title='Scop')
    seer: float | None = Field(None, title='Seer')
    heat_pump_type: str | None = Field(None, title='Heat Pump Type')
    reversible: bool | None = Field(None, title='Reversible')
    refrigerant: str | None = Field(None, title='Refrigerant')
    installation_date: str | None = Field(None, title='Installation Date')
    device: DeviceInSchema | None = None
    relationships: AssetRelationshipsInSchema | None = None


class ImportReportSchema(BaseModel):
    """
    Import operation report.
    """
    community_key: str = Field(..., title='Community Key')
    deleted: dict[str, int] | None = Field(None, title='Deleted')
    inserted: dict[str, int] | None = Field(None, title='Inserted')
    warnings: list[str] | None = Field(None, title='Warnings')


class LegalInfoInSchema(BaseModel):
    """
    Legal and administrative details.
    """
    class Config:
        extra = Extra.allow
    name: str | None = Field(None, title='Name')
    vat: str | None = Field(None, title='Vat')
    fiscal_code: str | None = Field(None, title='Fiscal Code')
    legal_form: str | None = Field(None, title='Legal Form')
    registration_number: str | None = Field(None, title='Registration Number')
    registered_office: str | None = Field(None, title='Registered Office')


class LinksInSchema(BaseModel):
    """
    Public URLs for the community.
    """
    class Config:
        extra = Extra.allow
    website: str | None = Field(None, title='Website')
    logo: str | None = Field(None, title='Logo')
    privacy_policy: str | None = Field(None, title='Privacy Policy')
    terms: str | None = Field(None, title='Terms')
    statute: str | None = Field(None, title='Statute')
    regulations: str | None = Field(None, title='Regulations')


class LoadAssetInSchema(BaseModel):
    """
    Load asset.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    load_type: str | None = Field(None, title='Load Type')
    rated_power: float | None = Field(None, title='Rated Power')
    min_power: float | None = Field(None, title='Min Power')
    controllable: bool | None = Field(None, title='Controllable')
    priority: str | None = Field(None, title='Priority')
    flexibility_kw: float | None = Field(None, title='Flexibility Kw')
    device: DeviceInSchema | None = None
    relationships: AssetRelationshipsInSchema | None = None


class LocationSchema(BaseModel):
    lat: float = Field(..., title='Lat')
    lon: float = Field(..., title='Lon')


class LocationInSchema(BaseModel):
    """
    Geographic location.
    """
    class Config:
        extra = Extra.allow
    lat: float = Field(..., title='Lat')
    lon: float = Field(..., title='Lon')


class MemberDetailSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')
    delivery_points: list[DeliveryPointSchema] | None = Field(None, title='Delivery Points')
    extra: dict[str, Any] | None = Field(None, title='MemberDetailExtra')
    created_at: str | None = Field(None, title='Created At')
    updated_at: str | None = Field(None, title='Updated At')


class MemberInCommunitySchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')
    status: str = Field(..., title='Status')


class MemberListItemSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')
    delivery_points_count: int | None = Field(0, title='Delivery Points Count')


class MemberPatchSchema(BaseModel):
    """
    Partial update. Absent fields are left alone, never cleared.

    `delivery_points` is deliberately absent: it is a JSONB list, and a patch
    that happened to omit it would otherwise read as "this member now has none".
    It has its own sub-resource.
    """
    user_id: str | None = Field(None, title='User Id')
    name: str | None = Field(None, title='Name')
    type: str | None = Field(None, title='Type')
    role: str | None = Field(None, title='Role')
    area: str | None = Field(None, title='Area')
    status: str | None = Field(None, title='Status')
    extra: dict[str, Any] | None = Field(None, title='Extra')


class MemberRefSchema(BaseModel):
    key: str = Field(..., title='Key')
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')


class MemberStatusChangeSchema(BaseModel):
    """
    Move a member through `pending → active → suspended → inactive`.
    """
    status: str = Field(..., title='Status')
    reason: str | None = Field(None, title='Reason')


class MetadataInSchema(BaseModel):
    """
    Registry metadata.
    """
    class Config:
        extra = Extra.allow
    created: str | None = Field(None, title='Created')
    updated: str | None = Field(None, title='Updated')
    updated_by: str | None = Field(None, title='Updated By')
    description: str | None = Field(None, title='Description')


class MeterAssetInSchema(BaseModel):
    """
    Meter asset.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    sensor_id: str = Field(..., title='Sensor Id')
    meter_type: str = Field(..., title='Meter Type')
    pod: str | None = Field(None, title='Pod')
    protocol: str | None = Field(None, title='Protocol')
    installation_date: str | None = Field(None, title='Installation Date')
    device: DeviceInSchema | None = None
    relationships: AssetRelationshipsInSchema | None = None


class MeterListItemSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    sensor_id: str | None = Field(None, title='Sensor Id')
    meter_type: str | None = Field(None, title='Meter Type')
    pod: str | None = Field(None, title='Pod')
    device: dict[str, Any] | None = Field(None, title='MeterListItemDevice')
    owner_key: str = Field(..., title='Owner Key')
    owner_user_id: str = Field(..., title='Owner User Id')


class MultiImportReportSchema(BaseModel):
    """
    Report for a bulk import of multiple bundles.
    """
    reports: list[ImportReportSchema] = Field(..., title='Reports')
    dry_run: bool | None = Field(False, title='Dry Run')


class OperatorInSchema(BaseModel):
    """
    Grid operator (DSO) active in this community.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    country: str | None = Field(None, title='Country')
    contact: str | None = Field(None, title='Contact')


class PVAssetInSchema(BaseModel):
    """
    PV system asset.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    rated_power: float | None = Field(None, title='Rated Power')
    panel_type: str | None = Field(None, title='Panel Type')
    inverter_power: float | None = Field(None, title='Inverter Power')
    orientation: float | None = Field(None, title='Orientation')
    tilt_angle: float | None = Field(None, title='Tilt Angle')
    installation_date: str | None = Field(None, title='Installation Date')
    device: DeviceInSchema | None = None
    relationships: AssetRelationshipsInSchema | None = None


class PaginatedResponseAssetListItemSchema(BaseModel):
    items: list[AssetListItemSchema] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class PaginatedResponseDeliveryPointWithOwnerSchema(BaseModel):
    items: list[DeliveryPointWithOwnerSchema] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class PaginatedResponseMemberListItemSchema(BaseModel):
    items: list[MemberListItemSchema] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class PaginatedResponseMeterListItemSchema(BaseModel):
    items: list[MeterListItemSchema] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class SensorIdsBatchRequestSchema(BaseModel):
    sensor_ids: list[str] = Field(..., title='Sensor Ids')


class SettingsInSchema(BaseModel):
    """
    Operational settings.
    """
    class Config:
        extra = Extra.allow
    timezone: str | None = Field(None, title='Timezone')
    currency: str | None = Field(None, title='Currency')
    energy_unit: str | None = Field(None, title='Energy Unit')
    power_unit: str | None = Field(None, title='Power Unit')


class StorageAssetInSchema(BaseModel):
    """
    Battery storage asset.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    capacity: float | None = Field(None, title='Capacity')
    max_charge_power: float | None = Field(None, title='Max Charge Power')
    max_discharge_power: float | None = Field(None, title='Max Discharge Power')
    battery_type: str | None = Field(None, title='Battery Type')
    round_trip_efficiency: float | None = Field(None, title='Round Trip Efficiency')
    installation_date: str | None = Field(None, title='Installation Date')
    device: DeviceInSchema | None = None
    relationships: AssetRelationshipsInSchema | None = None


class TopologyNodeSchema(BaseModel):
    id: str = Field(..., title='Id')
    type: str = Field(..., title='Type')
    name: str | None = Field(None, title='Name')
    operator: str | None = Field(None, title='Operator')
    parent: str | None = Field(None, title='Parent')
    area: dict[str, Any] | None = Field(None, title='TopologyNodeArea')


class TopologyNodeInSchema(BaseModel):
    """
    Grid topology node (substation, transformer, etc.).
    """
    class Config:
        extra = Extra.allow
    id: str = Field(..., title='Id')
    type: str = Field(..., title='Type')
    name: str | None = Field(None, title='Name')
    operator_id: str | None = Field(None, title='Operator Id')
    parent: str | None = Field(None, title='Parent')
    area: dict[str, Any] | None = Field(None, title='Area')


class TopologyResponseSchema(BaseModel):
    topology: list[TopologyNodeSchema] | None = Field(None, title='Topology')


class UserAssetSchema(BaseModel):
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    name: str = Field(..., title='Name')
    sensor_id: str | None = Field(None, title='Sensor Id')
    properties: dict[str, Any] | None = Field(None, title='UserAssetProperties')
    device: dict[str, Any] | None = Field(None, title='UserAssetDevice')
    relationships: dict[str, Any] | None = Field(None, title='UserAssetRelationships')


class UserAssetDetailSchema(BaseModel):
    key: str = Field(..., title='Key')
    asset_type: str = Field(..., title='Asset Type')
    name: str = Field(..., title='Name')
    sensor_id: str | None = Field(None, title='Sensor Id')
    properties: dict[str, Any] | None = Field(None, title='UserAssetDetailProperties')
    device: dict[str, Any] | None = Field(None, title='UserAssetDetailDevice')
    relationships: dict[str, Any] | None = Field(None, title='UserAssetDetailRelationships')
    extra: dict[str, Any] | None = Field(None, title='UserAssetDetailExtra')
    created_at: str | None = Field(None, title='Created At')
    updated_at: str | None = Field(None, title='Updated At')


class UserAssetsResponseSchema(BaseModel):
    items: list[UserAssetSchema] = Field(..., title='Items')
    total: int = Field(..., title='Total')


class UserCommunitySummarySchema(BaseModel):
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')


class UserDeliveryPointsResponseSchema(BaseModel):
    items: list[DeliveryPointSchema] = Field(..., title='Items')
    total: int = Field(..., title='Total')


class UserIdsBatchRequestSchema(BaseModel):
    """
    Members to resolve assets for.

    Bounded on purpose. A caller that can name ten thousand people in one
    request has a dump of the registry, not a lookup, and the endpoint is
    reachable by anything holding `rec-registry.lookup`.
    """
    user_ids: list[str] = Field(..., max_items=500, title='User Ids')


class UserMemberDetailSchema(BaseModel):
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')
    delivery_points: list[DeliveryPointSchema] | None = Field(None, title='Delivery Points')
    extra: dict[str, Any] | None = Field(None, title='UserMemberDetailExtra')
    created_at: str | None = Field(None, title='Created At')
    updated_at: str | None = Field(None, title='Updated At')


class UserMemberSummarySchema(BaseModel):
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')


class UserMembershipSchema(BaseModel):
    member: UserMemberSummarySchema
    community: UserCommunitySummarySchema
    delivery_points_count: int | None = Field(0, title='Delivery Points Count')
    assets_count: dict[str, int] | None = Field(None, title='UserMembershipAssetsCount')


class UserProfileSchema(BaseModel):
    sub: str = Field(..., title='Sub')
    email: str | None = Field(None, title='Email')
    name: str | None = Field(None, title='Name')
    preferred_username: str | None = Field(None, title='Preferred Username')


class ValidationErrorSchema(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class AreaSchema(BaseModel):
    name: str = Field(..., title='Name')
    location: LocationSchema | None = None
    geometry: dict[str, Any] | None = Field(None, title='Geometry')


class AreaInSchema(BaseModel):
    """
    Community area definition.
    """
    class Config:
        extra = Extra.allow
    name: str = Field(..., title='Name')
    topology: list[str] | None = Field(None, title='Topology')
    location: LocationInSchema | None = None
    geometry: dict[str, Any] | None = Field(None, title='Geometry')


class AreaUpsertSchema(BaseModel):
    """
    Create or replace one area of a community.
    """
    name: str = Field(..., title='Name')
    location: LocationSchema | None = None
    geometry: dict[str, Any] | None = Field(None, title='Geometry')
    topology: list[str] | None = Field(None, title='Topology')


class AssetCollectionInSchema(BaseModel):
    """
    Collection of assets organized by type.
    """
    class Config:
        extra = Extra.allow
    pv: dict[str, PVAssetInSchema] | None = Field(None, title='Pv')
    storage: dict[str, StorageAssetInSchema] | None = Field(None, title='Storage')
    meter: dict[str, MeterAssetInSchema] | None = Field(None, title='Meter')
    ev_charger: dict[str, EVChargerAssetInSchema] | None = Field(None, title='Ev Charger')
    heat_pump: dict[str, HeatPumpAssetInSchema] | None = Field(None, title='Heat Pump')
    load: dict[str, LoadAssetInSchema] | None = Field(None, title='Load')


class CommunityDetailSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    legal: dict[str, Any] | None = Field(None, title='CommunityDetailLegal')
    links: dict[str, Any] | None = Field(None, title='CommunityDetailLinks')
    contact: dict[str, Any] | None = Field(None, title='CommunityDetailContact')
    settings: dict[str, Any] | None = Field(None, title='CommunityDetailSettings')
    areas: dict[str, AreaSchema] | None = Field(None, title='CommunityDetailAreas')
    topology: list[TopologyNodeSchema] | None = Field(None, title='Topology')
    extra: dict[str, Any] | None = Field(None, title='CommunityDetailExtra')
    created_at: str | None = Field(None, title='Created At')
    updated_at: str | None = Field(None, title='Updated At')


class CommunityInSchema(BaseModel):
    """
    Community definition.
    """
    class Config:
        extra = Extra.allow
    id: str = Field(..., title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    legal: LegalInfoInSchema | None = None
    links: LinksInSchema | None = None
    contact: ContactInSchema | None = None
    settings: SettingsInSchema | None = None
    operators: dict[str, OperatorInSchema] | None = Field(None, title='Operators')
    areas: dict[str, AreaInSchema] | None = Field(None, title='Areas')
    topology: list[TopologyNodeInSchema] | None = Field(None, title='Topology')


class CommunityListItemSchema(BaseModel):
    id: str = Field(..., title='Id')
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    areas: dict[str, AreaSchema] | None = Field(None, title='CommunityListItemAreas')


class DeliveryPointLookupSchema(BaseModel):
    delivery_point: DeliveryPointSchema
    member: MemberRefSchema


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')


class LookupByDeliveryPointResponseSchema(BaseModel):
    community: CommunityRefSchema
    member: MemberRefSchema
    delivery_point: DeliveryPointSchema


class LookupBySensorIdResponseSchema(BaseModel):
    community: CommunityRefSchema
    member: MemberInCommunitySchema
    asset: AssetRefSchema


class LookupByUserIdResponseSchema(BaseModel):
    community: CommunityRefSchema
    member: MemberInCommunitySchema


class MemberCreateSchema(BaseModel):
    """
    Create one member. `key` is minted from the community's own numbering
    when omitted, so a caller with no opinion still gets `gl-00007` rather than
    something that reads as foreign in an exported bundle.
    """
    class Config:
        extra = Extra.allow
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    type: str | None = Field(None, title='Type')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')
    delivery_points: list[DeliveryPointInSchema] | None = Field(None, title='Delivery Points')
    assets: AssetCollectionInSchema | None = None
    key: str | None = Field(None, title='Key')


class MemberInSchema(BaseModel):
    """
    Community member.
    """
    class Config:
        extra = Extra.allow
    user_id: str = Field(..., title='User Id')
    name: str = Field(..., title='Name')
    type: str | None = Field(None, title='Type')
    role: str = Field(..., title='Role')
    area: str = Field(..., title='Area')
    status: str = Field(..., title='Status')
    delivery_points: list[DeliveryPointInSchema] | None = Field(None, title='Delivery Points')
    assets: AssetCollectionInSchema | None = None


class PaginatedResponseCommunityListItemSchema(BaseModel):
    items: list[CommunityListItemSchema] = Field(..., title='Items')
    next_cursor: str | None = Field(None, title='Next Cursor')


class RegistryBundleInSchema(BaseModel):
    """
    Complete registry bundle for import.

    Matches v0.4 structure.
    """
    class Config:
        extra = Extra.allow
    version: str | None = Field('1.0', title='Version')
    schema_version: str | None = Field('1.0', title='Schema Version')
    metadata: MetadataInSchema | None = None
    community: CommunityInSchema
    members: dict[str, MemberInSchema] | None = Field(None, title='Members')


class UserCommunityDetailSchema(BaseModel):
    key: str = Field(..., title='Key')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    legal: dict[str, Any] | None = Field(None, title='UserCommunityDetailLegal')
    links: dict[str, Any] | None = Field(None, title='UserCommunityDetailLinks')
    contact: dict[str, Any] | None = Field(None, title='UserCommunityDetailContact')
    settings: dict[str, Any] | None = Field(None, title='UserCommunityDetailSettings')
    areas: dict[str, AreaSchema] | None = Field(None, title='UserCommunityDetailAreas')
    topology: list[TopologyNodeSchema] | None = Field(None, title='Topology')
    your_area: str = Field(..., title='Your Area')
    your_role: str = Field(..., title='Your Role')


class UserMeResponseSchema(BaseModel):
    profile: UserProfileSchema
    membership: UserMembershipSchema | None = None


class ImportRequestSchema(BaseModel):
    """
    Import request payload.
    """
    bundle: RegistryBundleInSchema
    dry_run: bool | None = Field(False, title='Dry Run')
    force: bool | None = Field(False, title='Force')
