# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-08-15T15:46:55+00:00

from __future__ import annotations
from pydantic import BaseModel, Field


class BodyUploadSystemAdminUploadsPostSchema(BaseModel):
    file: bytes = Field(..., title='File')


class BodyUploadUserUploadPostSchema(BaseModel):
    file: bytes = Field(..., title='File')


class ChatRequestSchema(BaseModel):
    attachment_ids: list[str] | None = Field(None, title='Attachment Ids')
    conversation_id: str | None = Field(None, title='Conversation Id')
    include_citations: bool | None = Field(True, title='Include Citations')
    message: str = Field(..., title='Message')
    top_k: int | None = Field(5, title='Top K')


class HealthResponseSchema(BaseModel):
    status: str | None = Field('ok', title='Status')


class TrainingMaterialsSyncRequestSchema(BaseModel):
    target_ref: str | None = Field(None, description='Git commit SHA, tag, or ref to sync', title='Target Ref')


class UserInfoSchema(BaseModel):
    email: str | None = Field('', title='Email')
    first_name: str | None = Field('', title='First Name')
    full_name: str | None = Field('', title='Full Name')
    groups: list[str] | None = Field(None, title='Groups')
    is_admin: bool | None = Field(False, title='Is Admin')
    last_name: str | None = Field('', title='Last Name')
    user_id: str | None = Field('', title='User Id')
    username: str | None = Field('', title='Username')


class ValidationErrorSchema(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')
