# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-09-07T04:19:07+00:00

from __future__ import annotations
from pydantic import BaseModel, Field, constr
from datetime import datetime
from uuid import UUID
from typing import Any
from enum import Enum


class AuditLogReadSchema(BaseModel):
    action: str = Field(..., title='Action')
    actor_client_id: str | None = Field(..., title='Actor Client Id')
    actor_email: str | None = Field(..., title='Actor Email')
    actor_sub: str | None = Field(..., title='Actor Sub')
    actor_type: str = Field(..., title='Actor Type')
    created_at: datetime = Field(..., title='Created At')
    detail: str | None = Field(..., title='Detail')
    entity_id: str | None = Field(..., title='Entity Id')
    entity_type: str = Field(..., title='Entity Type')
    id: UUID = Field(..., title='Id')
    ip_address: str | None = Field(..., title='Ip Address')
    rec_slug: str | None = Field(..., title='Rec Slug')


class BodyExtractFromIdUploadApiRecSlugExtractIdPostSchema(BaseModel):
    files: list[str] = Field(..., title='Files')


class BodyExtractFromUploadApiRecSlugExtractPostSchema(BaseModel):
    files: list[str] = Field(..., title='Files')


class BodyUploadDocumentApiRecSlugSubmissionsSubmissionIdDocumentsPostSchema(BaseModel):
    file: str = Field(..., title='File')


class ConsentCreateSchema(BaseModel):
    gdpr_consent: bool = Field(..., title='Gdpr Consent')
    gdpr_consent_version: constr(max_length=20) = Field(..., title='Gdpr Consent Version')
    policy_consent: bool = Field(..., title='Policy Consent')
    policy_consent_version: constr(max_length=20) = Field(..., title='Policy Consent Version')
    statute_consent: bool = Field(..., title='Statute Consent')
    statute_consent_version: constr(max_length=20) = Field(..., title='Statute Consent Version')


class CsvExportRequestSchema(BaseModel):
    agreement_ref: str | None = Field(None, title='Agreement Ref')
    purpose: list[str] | None = Field([], title='Purpose')
    recipient_ref: str | None = Field(None, description='Who the data is being disclosed to. Naming one records a DataDisclosed provenance event; omit it for an internal dump.', title='Recipient Ref')


class DataSharingDecisionRequestSchema(BaseModel):
    """
    Grant or withdraw one offer.
    """
    enabled: bool = Field(..., title='Enabled')


class DocumentTypeSchema(Enum):
    utility_bill = 'utility_bill'
    gdpr_form = 'gdpr_form'
    policy_doc = 'policy_doc'
    statute_doc = 'statute_doc'
    id_card = 'id_card'
    other = 'other'


class EligibilityRequestSchema(BaseModel):
    address: str | None = Field(None, title='Address')
    lat: float | None = Field(None, title='Lat')
    lng: float | None = Field(None, title='Lng')


class EligibilityResponseSchema(BaseModel):
    country_code: str | None = Field(None, title='Country Code')
    eligible: bool = Field(..., title='Eligible')
    lat: float | None = Field(None, title='Lat')
    lng: float | None = Field(None, title='Lng')
    matched_rule: str | None = Field(None, title='Matched Rule')
    matched_value: str | None = Field(None, title='Matched Value')
    municipality: str | None = Field(None, title='Municipality')
    postal_code: str | None = Field(None, title='Postal Code')
    reason: str | None = Field(None, title='Reason')
    state: str | None = Field(None, title='State')


class ExtractionConfirmSchema(BaseModel):
    extracted_data: dict[str, Any] | None = Field(None, title='Extracted Data')


class ExtractionReadSchema(BaseModel):
    confirmed_at: datetime | None = Field(..., title='Confirmed At')
    confirmed_by_user: bool = Field(..., title='Confirmed By User')
    created_at: datetime = Field(..., title='Created At')
    document_id: UUID = Field(..., title='Document Id')
    extracted_data: dict[str, Any] = Field(..., title='Extracted Data')
    id: UUID = Field(..., title='Id')


class FindByAddressRequestSchema(BaseModel):
    address: str | None = Field(None, title='Address')
    lat: float | None = Field(None, title='Lat')
    lng: float | None = Field(None, title='Lng')


class PhoneConfirmRequestSchema(BaseModel):
    code: constr(min_length=4, max_length=10) = Field(..., title='Code')
    phone: constr(max_length=30) | None = Field(None, title='Phone')


class PhoneVerifyRequestSchema(BaseModel):
    """
    Request an OTP. `phone` defaults to the number already on the submission.
    """
    phone: constr(max_length=30) | None = Field(None, title='Phone')


class PhoneVerifyStatusSchema(BaseModel):
    phone_verified: bool = Field(..., title='Phone Verified')
    phone_verified_at: datetime | None = Field(None, title='Phone Verified At')
    sent: bool | None = Field(False, title='Sent')


class PodListRequestSchema(BaseModel):
    agreement_ref: str | None = Field(None, title='Agreement Ref')
    offer_id: str = Field(..., description='Consent is purpose-scoped: somebody who agreed to a different offer has not agreed to this handover.', title='Offer Id')
    purpose: list[str] | None = Field([], title='Purpose')
    recipient_ref: str = Field(..., title='Recipient Ref')


class RecAccessSchema(BaseModel):
    capabilities: list[str] = Field(..., title='Capabilities')
    name: str = Field(..., title='Name')
    organization: str | None = Field(..., title='Organization')
    slug: str = Field(..., title='Slug')


class RecStatsSchema(BaseModel):
    by_status: dict[str, int] = Field(..., title='By Status')
    rec_slug: str = Field(..., title='Rec Slug')
    submissions_with_failed_steps: int = Field(..., title='Submissions With Failed Steps')


class RetryRequestSchema(BaseModel):
    step: str | None = Field(None, description='One step to re-run. Omit to re-run every step that is not already succeeded or skipped.', title='Step')


class SharingStateSchema(Enum):
    """
    Why a member can or cannot decide anything, in one word.

    The states exist because collapsing them is what made the feature useless:
    a preregistered member reached the sharing screen and was told they had no
    dataspace identity, which was true and unactionable. Each of these has a
    different thing to say and a different thing to do next.
    """
    ok = 'ok'
    no_dataspace = 'no_dataspace'
    no_identity = 'no_identity'
    identity_conflict = 'identity_conflict'
    ambiguous_community = 'ambiguous_community'


class StepReadSchema(BaseModel):
    attempts: int = Field(..., title='Attempts')
    completed_at: datetime | None = Field(..., title='Completed At')
    detail: str | None = Field(..., title='Detail')
    external_ref: str | None = Field(..., title='External Ref')
    fail_closed: bool = Field(..., title='Fail Closed')
    label: str = Field(..., title='Label')
    last_error: str | None = Field(..., title='Last Error')
    started_at: datetime | None = Field(..., title='Started At')
    status: str = Field(..., title='Status')
    step: str = Field(..., title='Step')


class SubmissionStatusSchema(Enum):
    draft = 'draft'
    submitted = 'submitted'
    under_review = 'under_review'
    approved = 'approved'
    rejected = 'rejected'


class SubmissionUpdateSchema(BaseModel):
    data_sharing_consent: bool | None = Field(None, title='Data Sharing Consent')
    data_sharing_consent_locale: constr(max_length=20) | None = Field(None, title='Data Sharing Consent Locale')
    data_sharing_consent_offer_ids: list[str] | None = Field(None, title='Data Sharing Consent Offer Ids')
    data_sharing_consent_text_sha256: constr(max_length=64) | None = Field(None, title='Data Sharing Consent Text Sha256')
    data_sharing_consent_text_version: constr(max_length=200) | None = Field(None, title='Data Sharing Consent Text Version')
    email: constr(max_length=255) | None = Field(None, title='Email')
    extra_data: dict[str, Any] | None = Field(None, title='Extra Data')
    extracted_data: dict[str, Any] | None = Field(None, title='Extracted Data')
    first_name: constr(max_length=100) | None = Field(None, title='First Name')
    fiscal_code: constr(max_length=16) | None = Field(None, title='Fiscal Code')
    id_extracted_data: dict[str, Any] | None = Field(None, title='Id Extracted Data')
    keep_me_updated: bool | None = Field(None, title='Keep Me Updated')
    last_name: constr(max_length=100) | None = Field(None, title='Last Name')
    notes: constr(max_length=2000) | None = Field(None, title='Notes')
    phone: constr(max_length=30) | None = Field(None, title='Phone')
    pod_code: constr(max_length=20) | None = Field(None, title='Pod Code')
    status: SubmissionStatusSchema | None = None
    statute_consent: bool | None = Field(None, title='Statute Consent')
    supply_municipality: constr(max_length=200) | None = Field(None, title='Supply Municipality')


class TransitionRequestSchema(BaseModel):
    reason: constr(max_length=1000) | None = Field(None, description='Why. Required when rejecting — the participant is told, and an operator reopening the case months later needs to know.', title='Reason')
    target: SubmissionStatusSchema


class ValidationErrorSchema(BaseModel):
    ctx: dict[str, Any] | None = Field(None, title='Context')
    input: Any | None = Field(None, title='Input')
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class AdminMeSchema(BaseModel):
    email: str | None = Field(..., title='Email')
    locale: str | None = Field(..., title='Locale')
    name: str | None = Field(..., title='Name')
    organizations: list[str] = Field(..., title='Organizations')
    preferred_username: str | None = Field(..., title='Preferred Username')
    realm_groups: list[str] = Field(..., title='Realm Groups')
    recs: list[RecAccessSchema] = Field(..., title='Recs')
    sub: str = Field(..., title='Sub')
    subject_type: str = Field(..., title='Subject Type')


class DataSharingHistoryResponseSchema(BaseModel):
    """
    The member's own record of what happened with their data.
    """
    events: list[dict[str, Any]] | None = Field(None, title='Events')
    has_identity: bool = Field(..., title='Has Identity')
    state: SharingStateSchema


class DataSharingStatusResponseSchema(BaseModel):
    """
    Every offer this member's community publishes, with their decision on it.

    ``has_identity`` and ``offers`` are the shape `../celine-webapp` already
    serves to its frontend, kept so a relocation costs the UI nothing. ``state``
    is additive and says *why* `has_identity` is false — "your community is not
    in a dataspace" and "you have no credential yet" need different sentences and
    used to get the same one.

    ``identity`` carries the member's DID, their credential's role, and its
    issued/expires dates — enough to quote to a REC manager looking them up, and
    the only way a member learns a DID that was minted on their behalf. ``None``
    unless `state` is `ok`.

    **No credential is ever in here.** Not the `vc_jws`, which authenticates as
    the member, and not in any field added later.
    """
    has_identity: bool = Field(..., title='Has Identity')
    identity: dict[str, Any] | None = Field(None, title='Identity')
    offers: list[dict[str, Any]] | None = Field(None, title='Offers')
    state: SharingStateSchema


class DocumentReadSchema(BaseModel):
    created_at: datetime = Field(..., title='Created At')
    doc_type: DocumentTypeSchema
    id: UUID = Field(..., title='Id')
    mime_type: str = Field(..., title='Mime Type')
    original_filename: str = Field(..., title='Original Filename')
    size_bytes: int = Field(..., title='Size Bytes')
    submission_id: UUID = Field(..., title='Submission Id')


class EnablementReadSchema(BaseModel):
    state: str = Field(..., title='State')
    steps: list[StepReadSchema] = Field(..., title='Steps')
    submission_id: UUID = Field(..., title='Submission Id')


class HTTPValidationErrorSchema(BaseModel):
    detail: list[ValidationErrorSchema] | None = Field(None, title='Detail')


class SubmissionAdminReadSchema(BaseModel):
    consent_ip: str = Field(..., title='Consent Ip')
    created_at: datetime = Field(..., title='Created At')
    data_sharing_consent: bool = Field(..., title='Data Sharing Consent')
    data_sharing_consent_at: datetime | None = Field(..., title='Data Sharing Consent At')
    data_sharing_consent_locale: str | None = Field(..., title='Data Sharing Consent Locale')
    data_sharing_consent_offer_ids: list[str] | None = Field(..., title='Data Sharing Consent Offer Ids')
    data_sharing_consent_text_sha256: str | None = Field(..., title='Data Sharing Consent Text Sha256')
    data_sharing_consent_text_version: str | None = Field(..., title='Data Sharing Consent Text Version')
    data_sharing_issues: list[str] | None = Field([], title='Data Sharing Issues')
    dataspace_did: str | None = Field(..., title='Dataspace Did')
    dataspace_subject_id: str | None = Field(..., title='Dataspace Subject Id')
    dataspace_vc_id: str | None = Field(..., title='Dataspace Vc Id')
    dataspace_vc_issued_at: datetime | None = Field(..., title='Dataspace Vc Issued At')
    email: str | None = Field(..., title='Email')
    extra_data: dict[str, Any] | None = Field(..., title='Extra Data')
    extracted_data: dict[str, Any] | None = Field(..., title='Extracted Data')
    first_name: str | None = Field(..., title='First Name')
    fiscal_code: str | None = Field(..., title='Fiscal Code')
    gdpr_consent: bool = Field(..., title='Gdpr Consent')
    gdpr_consent_at: datetime | None = Field(..., title='Gdpr Consent At')
    gdpr_consent_version: str | None = Field(..., title='Gdpr Consent Version')
    id: UUID = Field(..., title='Id')
    id_extracted_data: dict[str, Any] | None = Field(..., title='Id Extracted Data')
    keep_me_updated: bool = Field(..., title='Keep Me Updated')
    last_name: str | None = Field(..., title='Last Name')
    notes: str | None = Field(..., title='Notes')
    phone: str | None = Field(..., title='Phone')
    phone_verified: bool = Field(..., title='Phone Verified')
    phone_verified_at: datetime | None = Field(..., title='Phone Verified At')
    pod_code: str | None = Field(..., title='Pod Code')
    policy_consent: bool = Field(..., title='Policy Consent')
    policy_consent_at: datetime | None = Field(..., title='Policy Consent At')
    policy_consent_version: str | None = Field(..., title='Policy Consent Version')
    rec_slug: str = Field(..., title='Rec Slug')
    ref: str = Field(..., title='Ref')
    share_provisioned: bool = Field(..., title='Share Provisioned')
    status: SubmissionStatusSchema
    statute_consent: bool = Field(..., title='Statute Consent')
    statute_consent_at: datetime | None = Field(..., title='Statute Consent At')
    statute_consent_version: str | None = Field(..., title='Statute Consent Version')
    supply_municipality: str | None = Field(..., title='Supply Municipality')
    updated_at: datetime = Field(..., title='Updated At')


class SubmissionCreatedReadSchema(BaseModel):
    created_at: datetime = Field(..., title='Created At')
    data_sharing_consent: bool = Field(..., title='Data Sharing Consent')
    data_sharing_consent_at: datetime | None = Field(..., title='Data Sharing Consent At')
    data_sharing_consent_locale: str | None = Field(..., title='Data Sharing Consent Locale')
    data_sharing_consent_offer_ids: list[str] | None = Field(..., title='Data Sharing Consent Offer Ids')
    data_sharing_consent_text_sha256: str | None = Field(..., title='Data Sharing Consent Text Sha256')
    data_sharing_consent_text_version: str | None = Field(..., title='Data Sharing Consent Text Version')
    email: str | None = Field(..., title='Email')
    extra_data: dict[str, Any] | None = Field(..., title='Extra Data')
    extracted_data: dict[str, Any] | None = Field(..., title='Extracted Data')
    first_name: str | None = Field(..., title='First Name')
    fiscal_code: str | None = Field(..., title='Fiscal Code')
    gdpr_consent: bool = Field(..., title='Gdpr Consent')
    gdpr_consent_at: datetime | None = Field(..., title='Gdpr Consent At')
    gdpr_consent_version: str | None = Field(..., title='Gdpr Consent Version')
    id: UUID = Field(..., title='Id')
    id_extracted_data: dict[str, Any] | None = Field(..., title='Id Extracted Data')
    keep_me_updated: bool = Field(..., title='Keep Me Updated')
    last_name: str | None = Field(..., title='Last Name')
    notes: str | None = Field(..., title='Notes')
    phone: str | None = Field(..., title='Phone')
    phone_verified: bool = Field(..., title='Phone Verified')
    phone_verified_at: datetime | None = Field(..., title='Phone Verified At')
    pod_code: str | None = Field(..., title='Pod Code')
    policy_consent: bool = Field(..., title='Policy Consent')
    policy_consent_at: datetime | None = Field(..., title='Policy Consent At')
    policy_consent_version: str | None = Field(..., title='Policy Consent Version')
    rec_slug: str = Field(..., title='Rec Slug')
    ref: str = Field(..., title='Ref')
    session_token: str = Field(..., title='Session Token')
    share_provisioned: bool = Field(..., title='Share Provisioned')
    status: SubmissionStatusSchema
    statute_consent: bool = Field(..., title='Statute Consent')
    statute_consent_at: datetime | None = Field(..., title='Statute Consent At')
    statute_consent_version: str | None = Field(..., title='Statute Consent Version')
    supply_municipality: str | None = Field(..., title='Supply Municipality')
    updated_at: datetime = Field(..., title='Updated At')


class SubmissionReadSchema(BaseModel):
    created_at: datetime = Field(..., title='Created At')
    data_sharing_consent: bool = Field(..., title='Data Sharing Consent')
    data_sharing_consent_at: datetime | None = Field(..., title='Data Sharing Consent At')
    data_sharing_consent_locale: str | None = Field(..., title='Data Sharing Consent Locale')
    data_sharing_consent_offer_ids: list[str] | None = Field(..., title='Data Sharing Consent Offer Ids')
    data_sharing_consent_text_sha256: str | None = Field(..., title='Data Sharing Consent Text Sha256')
    data_sharing_consent_text_version: str | None = Field(..., title='Data Sharing Consent Text Version')
    email: str | None = Field(..., title='Email')
    extra_data: dict[str, Any] | None = Field(..., title='Extra Data')
    extracted_data: dict[str, Any] | None = Field(..., title='Extracted Data')
    first_name: str | None = Field(..., title='First Name')
    fiscal_code: str | None = Field(..., title='Fiscal Code')
    gdpr_consent: bool = Field(..., title='Gdpr Consent')
    gdpr_consent_at: datetime | None = Field(..., title='Gdpr Consent At')
    gdpr_consent_version: str | None = Field(..., title='Gdpr Consent Version')
    id: UUID = Field(..., title='Id')
    id_extracted_data: dict[str, Any] | None = Field(..., title='Id Extracted Data')
    keep_me_updated: bool = Field(..., title='Keep Me Updated')
    last_name: str | None = Field(..., title='Last Name')
    notes: str | None = Field(..., title='Notes')
    phone: str | None = Field(..., title='Phone')
    phone_verified: bool = Field(..., title='Phone Verified')
    phone_verified_at: datetime | None = Field(..., title='Phone Verified At')
    pod_code: str | None = Field(..., title='Pod Code')
    policy_consent: bool = Field(..., title='Policy Consent')
    policy_consent_at: datetime | None = Field(..., title='Policy Consent At')
    policy_consent_version: str | None = Field(..., title='Policy Consent Version')
    rec_slug: str = Field(..., title='Rec Slug')
    ref: str = Field(..., title='Ref')
    share_provisioned: bool = Field(..., title='Share Provisioned')
    status: SubmissionStatusSchema
    statute_consent: bool = Field(..., title='Statute Consent')
    statute_consent_at: datetime | None = Field(..., title='Statute Consent At')
    statute_consent_version: str | None = Field(..., title='Statute Consent Version')
    supply_municipality: str | None = Field(..., title='Supply Municipality')
    updated_at: datetime = Field(..., title='Updated At')
